name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up .NET 10.0
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
      - name: Install tools
        run: |
          dotnet tool install dotnet-coverage --version 18.9.0
          dotnet tool install dotnet-sonarscanner --version 11.2.1
      - name: Report code coverage metrics to SonarQube Cloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet dotnet-sonarscanner begin /o:"aromppainen" /k:"ARomppainen_sat-solver" /d:sonar.token="$SONAR_TOKEN" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet build --no-incremental
          dotnet dotnet-coverage collect "tests/SatSolver.Dimacs.Tests/bin/Debug/net10.0/SatSolver.Dimacs.Tests" -f xml -o "coverage1.xml"
          dotnet dotnet-coverage collect "tests/SatSolver.Core.Tests/bin/Debug/net10.0/SatSolver.Core.Tests" -f xml -o "coverage2.xml"
          dotnet build --property:DefineConstants="USE_MAX_HEAP" --no-incremental
          dotnet dotnet-coverage collect "tests/SatSolver.Core.Tests/bin/Debug/net10.0/SatSolver.Core.Tests" -f xml -o "coverage3.xml"
          dotnet build --property:DefineConstants="USE_WATCHED_LITERALS_V2" --no-incremental
          dotnet dotnet-coverage collect "tests/SatSolver.Core.Tests/bin/Debug/net10.0/SatSolver.Core.Tests" -f xml -o "coverage4.xml"
          dotnet dotnet-coverage merge coverage*.xml -o "coverage.xml" -f "xml"
          dotnet dotnet-sonarscanner end /d:sonar.token="$SONAR_TOKEN"
