# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up .NET 10.0
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
      - name: Install tools
        run: |
          dotnet tool install dotnet-reportgenerator-globaltool --version 5.5.11
      - name: Generate coverage report
        run: |
          dotnet build
          tests/SatSolver.Dimacs.Tests/bin/Debug/net10.0/SatSolver.Dimacs.Tests --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml
          tests/SatSolver.Core.Tests/bin/Debug/net10.0/SatSolver.Core.Tests --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura1.xml
          dotnet build --property:DefineConstants="USE_MAX_HEAP"
          tests/SatSolver.Core.Tests/bin/Debug/net10.0/SatSolver.Core.Tests --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura2.xml
          dotnet build --property:DefineConstants="USE_WATCHED_LITERALS_V2"
          tests/SatSolver.Core.Tests/bin/Debug/net10.0/SatSolver.Core.Tests --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura3.xml
          dotnet reportgenerator -targetdir:"./pages/coverage-report" -reports:"tests/SatSolver.Dimacs.Tests/bin/Debug/net10.0/TestResults/coverage.cobertura.xml;tests/SatSolver.Core.Tests/bin/Debug/net10.0/TestResults/coverage.cobertura1.xml;tests/SatSolver.Core.Tests/bin/Debug/net10.0/TestResults/coverage.cobertura2.xml;tests/SatSolver.Core.Tests/bin/Debug/net10.0/TestResults/coverage.cobertura3.xml"
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './pages'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
